// import { Jost, Londrina_Outline } from "next/font/google";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/component/headerfooter/Header";
// import Footer from "@/component/headerfooter/Footer";
// import { Toaster } from "react-hot-toast";
// import Providers from "@/redux/Providers";
// import { getFooterData, getHeaderData, getHomeData } from "@/API/home";
// import { getTrendingProperties } from "@/API/property";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const jost = Jost({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-jost",
// });

// const londrinaOutline = Londrina_Outline({
//   subsets: ["latin"],
//   weight: "400",
//   variable: "--font-londrina-outline",
// });

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const [footerData, headerData] = await Promise.all([
//     getFooterData(),
//     getHeaderData(),
//     getHomeData(),
//     getTrendingProperties(),
//   ]);

//   return (
//     <html lang="en">
//       <body className={`${jost.variable} ${londrinaOutline.variable}`}>
//         <Providers>
//           <Header header={headerData.headers} company={headerData.company} />
//           <Toaster position="top-right" />
//           {children}
//           <Footer footer={footerData} />
//         </Providers>
//       </body>
//     </html>
//   );
// }

import { Jost, Londrina_Outline } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/component/headerfooter/Header";
import Footer from "@/component/headerfooter/Footer";
import { Toaster } from "react-hot-toast";
import Providers from "@/redux/Providers";
import { getFooterData, getHeaderData, getHomeData } from "@/API/home";
import { getTrendingProperties } from "@/API/property";

// ─── Font Configurations ───
const jost = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-jost",
});

const londrinaOutline = Londrina_Outline({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-londrina-outline",
});

// ─── Metadata ───
export const metadata: Metadata = {
  title: "Luxury Property Rentals",
  description: "Discover and book premium properties ",
  keywords: ["luxury properties", "rentals", "vacation homes"],
  authors: [{ name: "..." }],
};

// ─── Root Layout ───
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  try {
    // Fetch all data in parallel
    const [footerData, headerData, homeData, trendingProperties] =
      await Promise.all([
        getFooterData(),
        getHeaderData(),
        getHomeData(),
        getTrendingProperties(),
      ]);

    return (
      <html lang="en">
        <body className={jost.className}>
          <Providers>
            <Header
              header={headerData?.headers}
              company={headerData?.company}
            />
            <Toaster position="top-right" />
            {children}
            <Footer footer={footerData} />
          </Providers>
        </body>
      </html>
    );
  } catch (error) {
    console.error("Layout data fetch error:", error);

    // Fallback UI if data fetching fails
    return (
      <html lang="en">
        <body
          className={`${jost.variable} ${londrinaOutline.variable} font-jost`}
        >
          <Providers>
            <Toaster position="top-right" />
            {children}
          </Providers>
        </body>
      </html>
    );
  }
}
